/*
 * This file is generated by jOOQ.
 */
package net.sync.game.database.schema;


import net.sync.game.database.schema.tables.Charts;
import net.sync.game.database.schema.tables.Songs;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1974868282;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>charts</code>.
     */
    public final Charts CHARTS = Charts.CHARTS;

    /**
     * The table <code>songs</code>.
     */
    public final Songs SONGS = Songs.SONGS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Charts.CHARTS,
            Songs.SONGS);
    }
}
