/*
 * This file is generated by jOOQ.
*/
package net.sync.game.database.schema;


import net.sync.game.database.schema.tables.Charts;
import net.sync.game.database.schema.tables.Songs;
import net.sync.game.database.schema.tables.records.ChartsRecord;
import net.sync.game.database.schema.tables.records.SongsRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SongsRecord, Integer> IDENTITY_SONGS = Identities0.IDENTITY_SONGS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChartsRecord> PK_CHARTS = UniqueKeys0.PK_CHARTS;
    public static final UniqueKey<SongsRecord> PK_SONGS = UniqueKeys0.PK_SONGS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChartsRecord, SongsRecord> FK_CHARTS_SONGS_1 = ForeignKeys0.FK_CHARTS_SONGS_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<SongsRecord, Integer> IDENTITY_SONGS = createIdentity(Songs.SONGS, Songs.SONGS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChartsRecord> PK_CHARTS = createUniqueKey(Charts.CHARTS, "pk_charts", Charts.CHARTS.ID);
        public static final UniqueKey<SongsRecord> PK_SONGS = createUniqueKey(Songs.SONGS, "pk_songs", Songs.SONGS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ChartsRecord, SongsRecord> FK_CHARTS_SONGS_1 = createForeignKey(net.sync.game.database.schema.Keys.PK_SONGS, Charts.CHARTS, "fk_charts_songs_1", Charts.CHARTS.SONG_ID);
    }
}
