/*
 * This file is generated by jOOQ.
 */
package net.sync.game.database.schema;


import net.sync.game.database.schema.tables.Charts;
import net.sync.game.database.schema.tables.Songs;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>charts</code>.
     */
    public static final Charts CHARTS = Charts.CHARTS;

    /**
     * The table <code>songs</code>.
     */
    public static final Songs SONGS = Songs.SONGS;
}
