/*
 * This file is generated by jOOQ.
*/
package net.touchmania.game.database.schema;


import net.touchmania.game.database.schema.tables.Charts;
import net.touchmania.game.database.schema.tables.Songs;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>charts</code>.
     */
    public static final Charts CHARTS = net.touchmania.game.database.schema.tables.Charts.CHARTS;

    /**
     * The table <code>songs</code>.
     */
    public static final Songs SONGS = net.touchmania.game.database.schema.tables.Songs.SONGS;
}
